import Head from "next/head";
import React, { useEffect } from "react";

import { PomoStateProvider } from "../../utils/Context/PomoContext/Context";
import reducer, { initialState } from "../../utils/Context/PomoContext/reducer";
import ureducer, {
  initialState as userInitial,
} from "../../utils/Context/UserContext/reducer";
import preducer, {
  initialState as projInitial,
} from "../../utils/Context/ProjectContext/reducer";
import { UserStateProvider } from "../../utils/Context/UserContext/Context";
import { ProjectStateProvider } from "../../utils/Context/ProjectContext/Context";
import { NoiseStateProvider } from "../../utils/Context/NoiseContext/Context";
import noiseReducer, {
  initialState as noiseInitial,
} from "../../utils/Context/NoiseContext/reducer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { useSession } from "next-auth/react";
import Router from "next/router";
import NextProgress from "nextjs-progressbar";
import { shouldIgnore } from "@/utils/routes";
import { MediaKeysPreferenceProvider } from "@/utils/Context/MediaKeysPreferenceContext";
import { ThemeProvider, useTheme } from "@/utils/Context/ThemeContext";
import MediaSessionHandler from "../MediaSessionHandler";

interface Props {
  children: React.ReactNode;
}

function ThemedToastContainer() {
  const { resolvedTheme } = useTheme();
  return (
    <ToastContainer
      hideProgressBar
      newestOnTop={true}
      theme={resolvedTheme === "dark" ? "dark" : "light"}
    />
  );
}

export default function Shield({ children }: Props) {
  const { data: session, status } = useSession();

  useEffect(() => {
    if (!session && status != "loading" && !shouldIgnore(Router.pathname)) {
      Router.push("/login");
    }
  }, [session, status]);

  return (
    <ThemeProvider>
      <ProjectStateProvider reducer={preducer} initialState={projInitial}>
        <UserStateProvider reducer={ureducer} initialState={userInitial}>
          <PomoStateProvider reducer={reducer} initialState={initialState}>
            <NoiseStateProvider
              reducer={noiseReducer}
              initialState={noiseInitial}
            >
              <MediaKeysPreferenceProvider>
                <MediaSessionHandler />
                <NextProgress
                  color="#374151"
                  showOnShallow={false}
                  stopDelayMs={0}
                  options={{
                    showSpinner: false,
                  }}
                />

                <ThemedToastContainer />

                <Head>
                  <title>Pomodoro</title>
                  <meta
                    name="description"
                    content="Generated by create-t3-app"
                  />
                  <link rel="icon" href="/favicon.ico" />
                </Head>
                {children}
              </MediaKeysPreferenceProvider>
            </NoiseStateProvider>
          </PomoStateProvider>
        </UserStateProvider>
      </ProjectStateProvider>
    </ThemeProvider>
  );
}
