import Head from "next/head";
import React from "react";
import NextNProgress from "nextjs-progressbar";
import { PomoStateProvider } from "../../utils/Context/PomoContext/Context";
import reducer, { initialState } from "../../utils/Context/PomoContext/reducer";
import ureducer, {
  initialState as userInitial,
} from "../../utils/Context/UserContext/reducer";
import preducer, {
  initialState as projInitial,
} from "../../utils/Context/ProjectContext/reducer";
import { UserStateProvider } from "../../utils/Context/UserContext/Context";
import { ProjectStateProvider } from "../../utils/Context/ProjectContext/Context";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

interface Props {
  children: JSX.Element | React.ReactNode;
}

export default function index({ children }: Props) {
  return (
    <ProjectStateProvider reducer={preducer} initialState={projInitial}>
      <UserStateProvider reducer={ureducer} initialState={userInitial}>
        <PomoStateProvider reducer={reducer} initialState={initialState}>
          <NextNProgress
            color="#374151"
            showOnShallow={false}
            stopDelayMs={0}
            options={{
              showSpinner: false,
            }}
          />
          <ToastContainer hideProgressBar newestOnTop={true} />

          <Head>
            <title>Pomodoro</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          {children}
        </PomoStateProvider>
      </UserStateProvider>
    </ProjectStateProvider>
  );
}
